plugins {
    id "com.android.application"
}

android {
    namespace = "dev.obvious.minimallauncher"
    compileSdk = 37

    defaultConfig {
        applicationId = "dev.obvious.minimallauncher"
        minSdk = 29
        targetSdk = 36
        versionCode = 8
        versionName = "0.1.7"

        testInstrumentationRunner = "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
