plugins {
    id "com.android.application"
}

android {
    namespace = "dev.obvious.minimallauncher"
    compileSdk = 37

    defaultConfig {
        applicationId = "dev.obvious.minimallauncher"
        minSdk = 29
        targetSdk = 36
        versionCode = 23
        versionName = "0.9.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test:core:1.7.0"
    androidTestImplementation "androidx.test.ext:junit:1.3.0"
    androidTestImplementation "androidx.test:runner:1.7.0"
    androidTestImplementation "androidx.test.uiautomator:uiautomator:2.3.0"
}
